[build]
  base = "src/"
  publish = "out/"
  command = "npm run export:disconnected"
  
[[plugins]]
package = "netlify-plugin-cache-nextjs"

[template.environment]
  UNIFORM_PUBLISH_TARGET = ""
  NETLIFY_ACCESS_TOKEN = ""
  UNIFORM_API_KEY = ""
  UNIFORM_API_TOKEN = ""
  UNIFORM_API_URL = ""
  UNIFORM_DATA_URL = ""
  UNIFORM_API_SITENAME = ""
  UNIFORM_API_DEFAULT_LANGUAGE = "en"
  NPM_TOKEN = ""