[build]
  base = "src/"
  publish = "out/"
  command = "npm run export:disconnected"
  
[[plugins]]
package = "netlify-plugin-cache-nextjs"

[template.environment]
  UNIFORM_PUBLISH_TARGET = "Uniform API Site Name"
  NETLIFY_ACCESS_TOKEN = "Netlify Access Token"
  UNIFORM_API_KEY = "Uniform API Key"
  UNIFORM_API_TOKEN = "Unform API Token"
  UNIFORM_API_URL = "Uniform API URL"
  UNIFORM_DATA_URL = "Uniform Data URL"
  UNIFORM_API_SITENAME = "Uniform API Site Name"
  UNIFORM_API_DEFAULT_LANGUAGE = "Uniform API Default Language"
  NPM_TOKEN = "npm Token"